[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
g2_relay = "5aXXmvgFbT8rY1h2AzdG242w4EVStJYAz3nDKQ5bDGut"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
